version: '3.8'
services:
    sqlserver: 
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        ports:
            - '1433:1433'
        volumes:
            - sqldata:/var/opt/mssql
        container_name: sqlserver
        deploy:
          resources:
            reservations:
              cpus: '2'
              memory: 2GB
        image: mcr.microsoft.com/mssql/server
    web_app:
        container_name: web-app
        image: violetta1librarycr.azurecr.io/library
        domainname: violetta1
        ports:
          - '80:80'
        restart: on-failure

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: librarystorageacc13